language: java
sudo: false
cache:
  directories:
    - $HOME/.m2

# Don't cache own jars
before_cache:
  - rm -f $HOME/.m2/repository/com/peterphi
  
jdk:
  - oraclejdk8

env:
  global:
   # The next declration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Bgub+LcUBJJVDHKxdcKZnfvnxLZm8nBCh3YADVQ7aG8r58LPoGlYTYGro0cZ6Vov6GDzeaxX2Ovf6EH5ANlP/SUMHaZ7F3D3+NzqfxfeOPbGXUP5ZBYI2FoWXQdoO2S8Oy0GhUNZMRAfgeKZP2h5SIav2MdqGgDY8Sm+H1Oit9o="

addons:
  coverity_scan:
    project:
      name: "petergeneric/stdlib"
      description: "A guice-based application development library/framework"
    notification_email: peter@peterphi.com
    build_command_prepend: mvn clean
    build_command: mvn clean compile -DskipTests
    branch_pattern: coverity

