name: JDK25 Build and Test

on: [ push, pull_request ]


jobs:
  build:

    runs-on: ubuntu-latest
    env:
      TZ: "Europe/London"

    steps:
    - uses: actions/checkout@v2
    - name: Setup timezone
      uses: zcong1993/setup-timezone@f28e5fb1ca95077c81b67be53bcd1923de2175ed
      with:
        timezone: Europe/London
    - name: Set up JDK 25
      uses: actions/setup-java@v2
      with:
        java-version: 25
        distribution: zulu
 # Step that does that actual cache save and restore
    - uses: actions/cache@v4.2.2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -T3 -B test --file pom.xml
    - name: Publish Test Report
      if: ${{ always() }}
      uses: scacap/action-surefire-report@1a128e49c0585bc0b8e38e541ac3b6e35a5bc727